version: '3.8'
services:
  redis:
    image: redis:latest
    containner_name: redis_server
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  mongo:
    image: mongo:latest
    containner_name: mongo_server
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
